# Configuration file for TravisCI
os: linux
dist: xenial
language: python
python: "3.6"
notifications:
  email: false

# Only build pushes from the master branch. PRs are always built.
branches:
  only:
    - master

env:
  global:
    # Doctr deploy key for leouieda/leouieda.github.io
    - secure: "LiBewAMQZc4rrKrwM2p16Z/MzqNcha4CNVwBx0Oz6xN6BOh47zlWS0EIkfQtW/Pq5T7qFH0eF6jvYgk/91HyFaZm1CcvYOUUR2qa1AoKBbKlMire1D/8JqdZBoRRumvLwBXpE+mCEUrxzk4TtJLKU+tAoPP3oXMj+GRbYPTFKl4="

# Setup the build environment
install:
  # Install the requirements
  - pip install -r requirements.txt

script:
  # Build the website HTML
  - make

deploy:
  # Push the built HMTL to Github pages
  - provider: script
    script: doctr deploy . --built-docs _build --key-path .github_deploy_key.enc --deploy-repo leouieda/leouieda.github.io
    skip_cleanup: true
    on:
      branch: master
